version: '3.8'

services:
  startup-profiler:
    build: .
    container_name: startup-profiler-agent
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    stdin_open: true
    tty: true
    command: python main.py --interactive
    networks:
      - profiler-network

  # Optional: Streamlit UI service
  streamlit-ui:
    build: .
    container_name: startup-profiler-ui
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    networks:
      - profiler-network
    profiles:
      - ui

networks:
  profiler-network:
    driver: bridge

volumes:
  logs: